name: "GitHub Readme YouTube Cards"
author: "Jonah Lawrence"
description: "Workflow for displaying recent YouTube videos as SVG cards in your readme"
branding:
  icon: "grid"
  color: "red"

inputs:
  channel_id:
    description: "The channel ID to use for the feed"
    required: true
  comment_tag_name:
    description: "The name of the comment tag to use for the cards"
    required: false
    default: "YOUTUBE-CARDS"
  max_videos:
    description: "The maximum number of videos to display"
    required: false
    default: "6"
  base_url:
    description: "The base URL to use for the cards"
    required: false
    default: "https://youtube-cards.onrender.com/"
  committer_name:
    description: "The name of the committer"
    required: false
    default: "GitHub Actions"
  committer_email:
    description: "The email address of the committer"
    required: false
    default: "41898282+github-actions[bot]@users.noreply.github.com"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      shell: bash
      run: python -m pip install feedparser

    - name: Generate Readme Update
      id: "generate-readme-update"
      shell: bash
      run: echo ::set-output name=readme_update::$(python action.py --channel "${{ inputs.channel_id }}" --max-videos ${{ inputs.max_videos }} --base-url "${{ inputs.base_url }}")

    - name: Update README
      shell: bash
      env:
        BEGIN_TAG: "<!-- BEGIN ${{ inputs.comment_tag_name }} -->"
        END_TAG: "<!-- END ${{ inputs.comment_tag_name }} -->"
      run: |
        UPDATE=$(cat README.md | perl -0777 -pe 's#(${{ env.BEGIN_TAG }})(?:.|\n)*?(${{ env.END_TAG }})#${1}\n${{ steps.generate-readme-update.outputs.readme_update }}\n${2}#g')
        echo "${UPDATE}" > README.md

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "docs(readme): Update YouTube cards"
        committer_name: "${{ inputs.committer_name }}"
        committer_email: "${{ inputs.committer_email }}"
